### ISSUE TITLE
Lambert surface disappear in last release?

### ISSUE THREAD

**Issue by AStcherbinine** [kconnour/pyRT_DISORT#22]
Hi Kyle,

A quick question regarding the refactoring of the surface stuff in pyRT_DISORT from this August. Is there still a way to generate a Lambertian surface, or only Hapke now?

Thanks
Aurélien

**Comment by kconnour** [comment]
I refactored the code that makes a surface, so now there are just standalone functions that create the surface phase function arrays instead of an object with methods to create the proper surface. All the original functionality should be there (with fortran bug fixes!).

Regarding the Lambert surface, all my tests indicate that if you set the LAMBER=True when calling DISORT, it ignores whatever you put into rhou, rhoq, etc. So, you can create an array of zeros to appease DISORT, set LAMBER=True, and then you don't have to do anything else with the surface. As for Hapke, I created 3 functions that will create the 5 surface phase function arrays for the 3 types of Hapke surfaces that Mike had in disort_multi.

Let me know if this doesn't make sense, or if there's some functionality that seems to be missing.

**Comment by AStcherbinine** [comment]
Ok, thank you for the answer!
I was running some tests with Lambertian surface, I will try to do that.

But I think that regarding the initialization of the rhou, rhoq, etc arrays with zeros it may be useful to leave some function to initialize them with the proper shapes? I guess you already have these as that's what you were doing before?

**Comment by kconnour** [comment]
I have some protected functions in the surface module that will create those arrays. I suppose I can make them public for convenience for a Lambert surface. I'll try to remember to do that soon; if I forget, please ping me!

**Comment by kconnour** [comment]
Closed via #23
